import Papa from "papaparse";
import { format } from "date-fns";

export interface ExportMetadata {
  title: string;
  dateRange?: string;
  totalCount: number;
  totalAmount?: number;
  currency?: string;
}

/**
 * Professional CSV / Excel Export with Title, Header, Summary, and Timestamps
 */
export function exportToCSV(
  data: Record<string, any>[],
  filename: string,
  metadata: ExportMetadata
) {
  const generatedAt = format(new Date(), "yyyy-MM-dd HH:mm:ss");
  const currencySymbol = metadata.currency || "₹";

  // 1. Meta header rows
  const metaRows = [
    ["FINANCEOS - FINANCIAL REPORT & STATEMENT"],
    [`Report Title: ${metadata.title}`],
    [`Generated On: ${generatedAt}`],
    [`Filter Period: ${metadata.dateRange || "All Time"}`],
    [`Total Records: ${metadata.totalCount}`],
    metadata.totalAmount !== undefined
      ? [`Total Net Amount: ${currencySymbol} ${metadata.totalAmount.toLocaleString("en-IN")}`]
      : [],
    [], // Blank separator
  ];

  const csvMeta = Papa.unparse(metaRows.filter((r) => r.length > 0));
  const csvData = Papa.unparse(data);
  const fullCSV = `${csvMeta}\n\n${csvData}\n\n"CONFIDENTIAL - GENERATED BY FINANCEOS PERSONAL FINANCE MANAGER"`;

  const blob = new Blob([fullCSV], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `${filename}-${format(new Date(), "yyyy-MM-dd")}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Professional Printable PDF Export with Logo, Financial Summary, Table & Footer
 */
export function exportToPDF(
  data: Record<string, any>[],
  metadata: ExportMetadata,
  columns: { key: string; label: string }[]
) {
  const generatedAt = format(new Date(), "dd MMM yyyy, HH:mm:ss");
  const currencySymbol = metadata.currency || "₹";

  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${metadata.title} - FinanceOS</title>
        <style>
          @page { size: A4; margin: 15mm; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            color: #1e293b;
            background: #ffffff;
            margin: 0;
            padding: 20px;
            font-size: 12px;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 15px;
            margin-bottom: 20px;
          }
          .brand {
            display: flex;
            align-items: center;
            gap: 8px;
          }
          .brand-logo {
            width: 32px;
            height: 32px;
            background: #2563eb;
            color: #ffffff;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 18px;
            font-weight: bold;
          }
          .brand-name {
            font-size: 20px;
            font-weight: 800;
            color: #0f172a;
          }
          .doc-info {
            text-align: right;
          }
          .doc-title {
            font-size: 18px;
            font-weight: 700;
            color: #1e40af;
            margin: 0 0 4px 0;
          }
          .doc-meta {
            color: #64748b;
            font-size: 11px;
          }
          .summary-card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 12px 16px;
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
          }
          .summary-item {
            display: flex;
            flex-direction: column;
          }
          .summary-label {
            font-size: 10px;
            color: #64748b;
            text-transform: uppercase;
            font-weight: 600;
          }
          .summary-value {
            font-size: 15px;
            font-weight: 700;
            color: #0f172a;
            margin-top: 2px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
          }
          th {
            background: #f1f5f9;
            color: #475569;
            font-weight: 600;
            text-align: left;
            padding: 8px 10px;
            border-bottom: 1px solid #cbd5e1;
            font-size: 11px;
            text-transform: uppercase;
          }
          td {
            padding: 8px 10px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 11px;
          }
          tr:nth-child(even) {
            background: #fafafa;
          }
          .amount-income { color: #16a34a; font-weight: 600; }
          .amount-expense { color: #dc2626; font-weight: 600; }
          .amount-transfer { color: #475569; font-weight: 600; }
          .footer {
            border-top: 1px solid #e2e8f0;
            padding-top: 12px;
            display: flex;
            justify-content: space-between;
            color: #94a3b8;
            font-size: 10px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">
            <div class="brand-logo">₹</div>
            <div>
              <div class="brand-name">FinanceOS</div>
              <div style="font-size: 10px; color: #64748b;">Personal Finance & Money Manager</div>
            </div>
          </div>
          <div class="doc-info">
            <h1 class="doc-title">${metadata.title}</h1>
            <div class="doc-meta">Generated: ${generatedAt}</div>
            <div class="doc-meta">Period: ${metadata.dateRange || "All Time"}</div>
          </div>
        </div>

        <div class="summary-card">
          <div class="summary-item">
            <span class="summary-label">Total Records</span>
            <span class="summary-value">${metadata.totalCount} items</span>
          </div>
          ${
            metadata.totalAmount !== undefined
              ? `
          <div class="summary-item">
            <span class="summary-label">Total Net Amount</span>
            <span class="summary-value">${currencySymbol} ${metadata.totalAmount.toLocaleString("en-IN")}</span>
          </div>`
              : ""
          }
          <div class="summary-item">
            <span class="summary-label">Report Status</span>
            <span class="summary-value" style="color: #16a34a;">Verified & Complete</span>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              ${columns.map((c) => `<th>${c.label}</th>`).join("")}
            </tr>
          </thead>
          <tbody>
            ${data
              .map(
                (row) => `
              <tr>
                ${columns
                  .map((col) => {
                    const val = row[col.key] ?? "-";
                    let cls = "";
                    if (col.key === "amount" || col.key === "formattedAmount") {
                      if (row.type === "income") cls = 'class="amount-income"';
                      else if (row.type === "expense") cls = 'class="amount-expense"';
                      else cls = 'class="amount-transfer"';
                    }
                    return `<td ${cls}>${val}</td>`;
                  })
                  .join("")}
              </tr>`
              )
              .join("")}
          </tbody>
        </table>

        <div class="footer">
          <div>FinanceOS • Academic & Enterprise Financial Dashboard</div>
          <div>Confidential Document • Page 1 of 1</div>
        </div>

        <script>
          window.onload = function() {
            window.print();
          }
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}
